### ISSUE TITLE
`keyup` listener

### ISSUE THREAD

**Issue by silverwind** [RobertWHurst/Keystrokes#18]
**Is your feature request related to a problem? Please describe.**

I'd like to track the "down" state of the shift key, and for that a way to define a `keyUp` listener would be necessary. With `keyboardjs` I do:

```js
let shiftDown = false;
keyboardjs.bind("shift", () => {shiftDown = true});
keyboardjs.bind("shift", null, () => {shiftDown = false});
```

**Describe the solution you'd like**

Some way to define for which event to listen, for example with an options argument:

```js
bindKey("shift", () => {}, {event: "keydown"});
bindKey("shift", () => {}, {event: "keyup"});
```

**Comment by RobertWHurst** [comment]
Hi @silverwind. Indeed this is important functionality. It is actually already possible to do this. There is a [section on this in the readme](https://docs.google.com/document/d/1xVjcqJZurR_AcYKZ_DKGjZVKhuWwn7OQbTe6O-FKv70/edit). The gist is that you can pass an object as a handler instead of a function. The object has three optional properties. onPressed is essentially keydown, onPressedWithRepeat is the same thing, but calls the handler repeatedly (just like the browser), and onReleased is essentially keyup.

Here is an example:

```js
bindKey('shift', {
  onPressed: () => console.log('keydown'),
  onReleased: () => console.log('keyup'),
})

bindKeyCombo('shift > b', {
  onPressed: () => console.log('keydown'),
  onReleased: () => console.log('keyup'),
})
```

Does that solve you're problem?

**Comment by RobertWHurst** [comment]
Going to close for now, but we reopen if need be.

**Comment by RobertWHurst** [comment]
No problem at all, glad to help. 😁
