### ISSUE TITLE
`preventDefault` seems to have no effect

### ISSUE THREAD

**Issue by silverwind** [RobertWHurst/Keystrokes#19]
**Describe the bug**

I'd like to prevent the browser from presenting a "Save Page" dialog when pressingh Ctrl/Cmd + S. With [mousetrap](https://github.com/ccampbell/mousetrap), this is possible via simple `e.preventDefault()`, but this library does not expose such a function and trying to to it on the various `originalEvent` seems to not work at all.

**To Reproduce**
1. Open https://codesandbox.io/s/admiring-lamport-jh8k7h?file=/src/index.js
2. Focus the preview frame, hit "Ctrl + S" or "Cmd + S"

**Expected behavior**

No "Save Page" dialog to be shown.

**Additional context**

A more ergonomic `e.preventDefault` without having to use `originalEvent` would be nice.

**Comment by silverwind** [comment]
For reference, [here](https://codesandbox.io/s/morning-snowflake-6p76qh?file=/src/index.js) is a working demo with mousetrap.

What may also be a bug here is that the Ctrl+S combo is to not being captured on at least Chrome and Safari on MacOS, while in mousetrap, it is.

**Comment by silverwind** [comment]
I see, thanks. Maybe you could also for convenience expose a `preventDefault` function directly on the returned event because I'm confused whether I'm supposed to use `finalKeyEvent.originalEvent` or iterate `e.keyEvents` in this case.

**Comment by RobertWHurst** [comment]
I'm thinking I'll introduce a third argument which will take options for the binding. These options will be passed to the binder logic and will be generic based on the binder used. In the case of the browser binder, preventDefault will be an option, and since this library is about keyboard bindings and you likely want to always call preventDefault, this option will default to true, but can be set to false explicitly.

Prevent default called:
```
bindCombo('shift > s', handler)
```

Prevent default not called:
```
bindCombo('shift > s', handler, { preventDefault: false })
```

**Comment by RobertWHurst** [comment]
So after some experimentation, I've decided to remove the combo update batching. It will resolve this issue and any other event interaction related issues in the browser and otherwise. I've also added `preventDefault` to the browser event so you don't need to reach into the original event to call it. Checkout #20 if you're curious.

**Comment by RobertWHurst** [comment]
@silverwind ok, just released 1.2.0. You will need to reach into the finalKeyEvent property and call prevent default.

```ts
bindKeyCombo('ctrl > s', (event) => {
  event.finalKeyEvent.preventDefault()
  // ...
})
```

Let me know if you have any further issues. Thanks for raising this issue.

**Comment by silverwind** [comment]
Thanks, `preventDefault` works and save dialog is prevented. Updated demo:

https://codesandbox.io/s/quizzical-nightingale-c6t37s

There is another issue related to Control key on Mac, I will open a separate issue for it.

**Comment by silverwind** [comment]
Actually I may have spoken to soon, if I input `Command+s` in the demo above two times in a row, it seems to only prevent the first default action, the second time it fails to prevent the save dialog.

**Comment by RobertWHurst** [comment]
Hmm, this might be due to a different issue. Likely related to how the meta/command key is handled by Keystrokes on mac; on macOS the command key does not properly fire a keyup event. There is some special logic to handle this issue in src/browser-bindings.ts. I have a mac at home, but I'm away this week. I should be able to take a look when I get back around friday.

Edit: just saw your edit. I'll follow up with you in that issue.

**Comment by silverwind** [comment]
Thanks. Yes, this is most definitely a Mac-only issue. It seems like something inside the module breaks after the first entry of a sequence with the command key.

No hurries, I'll continue using mousetrap in my project until this is sorted out.

**Comment by noahbrom** [comment]
Hi @RobertWHurst 

I'm trying to test the behavior of preventDefault in a simple unit test with keystrokes.press(). The binding works as expected in the browser, but the unit test fails with the following error: 

TypeError: e.finalKeyEvent.preventDefault is not a function.

I was experimenting with @silverwind 's code, and it can be found here: https://codesandbox.io/s/blazing-silence-6pn9np?file=/src/test.spec.ts

Thanks!

**Comment by RobertWHurst** [comment]
Ah yes, I see the issue.

By default Keystrokes uses the browser bindings, but the test wrapper for creating a test instance of Keystrokes does not implement the browser bindings. Keystrokes allows setting up any bindings you like, that way it can be used in electron, or games or really anything else for that matter, in a way that is agnostic about how the events are generated. I built the test instance for building keystrokes own unit tests (minus the browser binding tests), but I didn't consider the fact that most people will need a test instance that matches the browser bindings. I'll likely introduce defaults to the test instance that match the browser bindings, and at the same time allow passing overrides.

Let's open another issue for this.
